export const languages = [
    { code: 'EN', description: 'English' },
    { code: 'DE', description: 'Deutsch' },
    { code: 'FR', description: 'Français' },
    { code: 'IT', description: 'Italiano' },
    { code: 'ES', description: 'Español' },
]

export const roles = [
    { id: 'ADMIN', description: 'Admin User' },
    { id: 'PROF', description: 'Professional User' },
    { id: 'STANDARD', description: 'Standard User' },
]

export const oppStatuses = [
    { id: 'Open', description: 'Open' },
    { id: 'Won', description: 'Won' },
    { id: 'Lost', description: 'Lost' },
]

export const priorities = [
    { id: 'Low', description: 'Low' },
    { id: 'Medium', description: 'Medium' },
    { id: 'High', description: 'High' },
    { id: 'Very High', description: 'Very High' },
]

export const taskStatuses = [
    { id: 'Not Started', description: 'Not Started' },
    { id: 'In Progress', description: 'In Progress' },
    { id: 'Completed', description: 'Completed' },
]

//https://gist.githubusercontent.com/keeguon/2310008/raw/bdc2ce1c1e3f28f9cab5b4393c7549f38361be4e/countries.json
export const countries = [
    { name: 'Afghanistan', code: 'AF' },
    { name: 'Åland Islands', code: 'AX' },
    { name: 'Albania', code: 'AL' },
    { name: 'Algeria', code: 'DZ' },
    { name: 'American Samoa', code: 'AS' },
    { name: 'AndorrA', code: 'AD' },
    { name: 'Angola', code: 'AO' },
    { name: 'Anguilla', code: 'AI' },
    { name: 'Antarctica', code: 'AQ' },
    { name: 'Antigua and Barbuda', code: 'AG' },
    { name: 'Argentina', code: 'AR' },
    { name: 'Armenia', code: 'AM' },
    { name: 'Aruba', code: 'AW' },
    { name: 'Australia', code: 'AU' },
    { name: 'Austria', code: 'AT' },
    { name: 'Azerbaijan', code: 'AZ' },
    { name: 'Bahamas', code: 'BS' },
    { name: 'Bahrain', code: 'BH' },
    { name: 'Bangladesh', code: 'BD' },
    { name: 'Barbados', code: 'BB' },
    { name: 'Belarus', code: 'BY' },
    { name: 'Belgium', code: 'BE' },
    { name: 'Belize', code: 'BZ' },
    { name: 'Benin', code: 'BJ' },
    { name: 'Bermuda', code: 'BM' },
    { name: 'Bhutan', code: 'BT' },
    { name: 'Bolivia', code: 'BO' },
    { name: 'Bosnia and Herzegovina', code: 'BA' },
    { name: 'Botswana', code: 'BW' },
    { name: 'Bouvet Island', code: 'BV' },
    { name: 'Brazil', code: 'BR' },
    { name: 'British Indian Ocean Territory', code: 'IO' },
    { name: 'Brunei Darussalam', code: 'BN' },
    { name: 'Bulgaria', code: 'BG' },
    { name: 'Burkina Faso', code: 'BF' },
    { name: 'Burundi', code: 'BI' },
    { name: 'Cambodia', code: 'KH' },
    { name: 'Cameroon', code: 'CM' },
    { name: 'Canada', code: 'CA' },
    { name: 'Cape Verde', code: 'CV' },
    { name: 'Cayman Islands', code: 'KY' },
    { name: 'Central African Republic', code: 'CF' },
    { name: 'Chad', code: 'TD' },
    { name: 'Chile', code: 'CL' },
    { name: 'China', code: 'CN' },
    { name: 'Christmas Island', code: 'CX' },
    { name: 'Cocos (Keeling) Islands', code: 'CC' },
    { name: 'Colombia', code: 'CO' },
    { name: 'Comoros', code: 'KM' },
    { name: 'Congo', code: 'CG' },
    { name: 'Congo, The Democratic Republic of the', code: 'CD' },
    { name: 'Cook Islands', code: 'CK' },
    { name: 'Costa Rica', code: 'CR' },
    { name: 'Cote D\'Ivoire', code: 'CI' },
    { name: 'Croatia', code: 'HR' },
    { name: 'Cuba', code: 'CU' },
    { name: 'Cyprus', code: 'CY' },
    { name: 'Czech Republic', code: 'CZ' },
    { name: 'Denmark', code: 'DK' },
    { name: 'Djibouti', code: 'DJ' },
    { name: 'Dominica', code: 'DM' },
    { name: 'Dominican Republic', code: 'DO' },
    { name: 'Ecuador', code: 'EC' },
    { name: 'Egypt', code: 'EG' },
    { name: 'El Salvador', code: 'SV' },
    { name: 'Equatorial Guinea', code: 'GQ' },
    { name: 'Eritrea', code: 'ER' },
    { name: 'Estonia', code: 'EE' },
    { name: 'Ethiopia', code: 'ET' },
    { name: 'Falkland Islands (Malvinas)', code: 'FK' },
    { name: 'Faroe Islands', code: 'FO' },
    { name: 'Fiji', code: 'FJ' },
    { name: 'Finland', code: 'FI' },
    { name: 'France', code: 'FR' },
    { name: 'French Guiana', code: 'GF' },
    { name: 'French Polynesia', code: 'PF' },
    { name: 'French Southern Territories', code: 'TF' },
    { name: 'Gabon', code: 'GA' },
    { name: 'Gambia', code: 'GM' },
    { name: 'Georgia', code: 'GE' },
    { name: 'Germany', code: 'DE' },
    { name: 'Ghana', code: 'GH' },
    { name: 'Gibraltar', code: 'GI' },
    { name: 'Greece', code: 'GR' },
    { name: 'Greenland', code: 'GL' },
    { name: 'Grenada', code: 'GD' },
    { name: 'Guadeloupe', code: 'GP' },
    { name: 'Guam', code: 'GU' },
    { name: 'Guatemala', code: 'GT' },
    { name: 'Guernsey', code: 'GG' },
    { name: 'Guinea', code: 'GN' },
    { name: 'Guinea-Bissau', code: 'GW' },
    { name: 'Guyana', code: 'GY' },
    { name: 'Haiti', code: 'HT' },
    { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
    { name: 'Holy See (Vatican City State)', code: 'VA' },
    { name: 'Honduras', code: 'HN' },
    { name: 'Hong Kong', code: 'HK' },
    { name: 'Hungary', code: 'HU' },
    { name: 'Iceland', code: 'IS' },
    { name: 'India', code: 'IN' },
    { name: 'Indonesia', code: 'ID' },
    { name: 'Iran, Islamic Republic Of', code: 'IR' },
    { name: 'Iraq', code: 'IQ' },
    { name: 'Ireland', code: 'IE' },
    { name: 'Isle of Man', code: 'IM' },
    { name: 'Israel', code: 'IL' },
    { name: 'Italy', code: 'IT' },
    { name: 'Jamaica', code: 'JM' },
    { name: 'Japan', code: 'JP' },
    { name: 'Jersey', code: 'JE' },
    { name: 'Jordan', code: 'JO' },
    { name: 'Kazakhstan', code: 'KZ' },
    { name: 'Kenya', code: 'KE' },
    { name: 'Kiribati', code: 'KI' },
    { name: 'Korea, Democratic People\'S Republic of', code: 'KP' },
    { name: 'Korea, Republic of', code: 'KR' },
    { name: 'Kuwait', code: 'KW' },
    { name: 'Kyrgyzstan', code: 'KG' },
    { name: 'Lao People\'S Democratic Republic', code: 'LA' },
    { name: 'Latvia', code: 'LV' },
    { name: 'Lebanon', code: 'LB' },
    { name: 'Lesotho', code: 'LS' },
    { name: 'Liberia', code: 'LR' },
    { name: 'Libyan Arab Jamahiriya', code: 'LY' },
    { name: 'Liechtenstein', code: 'LI' },
    { name: 'Lithuania', code: 'LT' },
    { name: 'Luxembourg', code: 'LU' },
    { name: 'Macao', code: 'MO' },
    { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
    { name: 'Madagascar', code: 'MG' },
    { name: 'Malawi', code: 'MW' },
    { name: 'Malaysia', code: 'MY' },
    { name: 'Maldives', code: 'MV' },
    { name: 'Mali', code: 'ML' },
    { name: 'Malta', code: 'MT' },
    { name: 'Marshall Islands', code: 'MH' },
    { name: 'Martinique', code: 'MQ' },
    { name: 'Mauritania', code: 'MR' },
    { name: 'Mauritius', code: 'MU' },
    { name: 'Mayotte', code: 'YT' },
    { name: 'Mexico', code: 'MX' },
    { name: 'Micronesia, Federated States of', code: 'FM' },
    { name: 'Moldova, Republic of', code: 'MD' },
    { name: 'Monaco', code: 'MC' },
    { name: 'Mongolia', code: 'MN' },
    { name: 'Montserrat', code: 'MS' },
    { name: 'Morocco', code: 'MA' },
    { name: 'Mozambique', code: 'MZ' },
    { name: 'Myanmar', code: 'MM' },
    { name: 'Namibia', code: 'NA' },
    { name: 'Nauru', code: 'NR' },
    { name: 'Nepal', code: 'NP' },
    { name: 'Netherlands', code: 'NL' },
    { name: 'Netherlands Antilles', code: 'AN' },
    { name: 'New Caledonia', code: 'NC' },
    { name: 'New Zealand', code: 'NZ' },
    { name: 'Nicaragua', code: 'NI' },
    { name: 'Niger', code: 'NE' },
    { name: 'Nigeria', code: 'NG' },
    { name: 'Niue', code: 'NU' },
    { name: 'Norfolk Island', code: 'NF' },
    { name: 'Northern Mariana Islands', code: 'MP' },
    { name: 'Norway', code: 'NO' },
    { name: 'Oman', code: 'OM' },
    { name: 'Pakistan', code: 'PK' },
    { name: 'Palau', code: 'PW' },
    { name: 'Palestinian Territory, Occupied', code: 'PS' },
    { name: 'Panama', code: 'PA' },
    { name: 'Papua New Guinea', code: 'PG' },
    { name: 'Paraguay', code: 'PY' },
    { name: 'Peru', code: 'PE' },
    { name: 'Philippines', code: 'PH' },
    { name: 'Pitcairn', code: 'PN' },
    { name: 'Poland', code: 'PL' },
    { name: 'Portugal', code: 'PT' },
    { name: 'Puerto Rico', code: 'PR' },
    { name: 'Qatar', code: 'QA' },
    { name: 'Reunion', code: 'RE' },
    { name: 'Romania', code: 'RO' },
    { name: 'Russian Federation', code: 'RU' },
    { name: 'RWANDA', code: 'RW' },
    { name: 'Saint Helena', code: 'SH' },
    { name: 'Saint Kitts and Nevis', code: 'KN' },
    { name: 'Saint Lucia', code: 'LC' },
    { name: 'Saint Pierre and Miquelon', code: 'PM' },
    { name: 'Saint Vincent and the Grenadines', code: 'VC' },
    { name: 'Samoa', code: 'WS' },
    { name: 'San Marino', code: 'SM' },
    { name: 'Sao Tome and Principe', code: 'ST' },
    { name: 'Saudi Arabia', code: 'SA' },
    { name: 'Senegal', code: 'SN' },
    { name: 'Serbia and Montenegro', code: 'CS' },
    { name: 'Seychelles', code: 'SC' },
    { name: 'Sierra Leone', code: 'SL' },
    { name: 'Singapore', code: 'SG' },
    { name: 'Slovakia', code: 'SK' },
    { name: 'Slovenia', code: 'SI' },
    { name: 'Solomon Islands', code: 'SB' },
    { name: 'Somalia', code: 'SO' },
    { name: 'South Africa', code: 'ZA' },
    { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
    { name: 'Spain', code: 'ES' },
    { name: 'Sri Lanka', code: 'LK' },
    { name: 'Sudan', code: 'SD' },
    { name: 'Suriname', code: 'SR' },
    { name: 'Svalbard and Jan Mayen', code: 'SJ' },
    { name: 'Swaziland', code: 'SZ' },
    { name: 'Sweden', code: 'SE' },
    { name: 'Switzerland', code: 'CH' },
    { name: 'Syrian Arab Republic', code: 'SY' },
    { name: 'Taiwan, Province of China', code: 'TW' },
    { name: 'Tajikistan', code: 'TJ' },
    { name: 'Tanzania, United Republic of', code: 'TZ' },
    { name: 'Thailand', code: 'TH' },
    { name: 'Timor-Leste', code: 'TL' },
    { name: 'Togo', code: 'TG' },
    { name: 'Tokelau', code: 'TK' },
    { name: 'Tonga', code: 'TO' },
    { name: 'Trinidad and Tobago', code: 'TT' },
    { name: 'Tunisia', code: 'TN' },
    { name: 'Turkey', code: 'TR' },
    { name: 'Turkmenistan', code: 'TM' },
    { name: 'Turks and Caicos Islands', code: 'TC' },
    { name: 'Tuvalu', code: 'TV' },
    { name: 'Uganda', code: 'UG' },
    { name: 'Ukraine', code: 'UA' },
    { name: 'United Arab Emirates', code: 'AE' },
    { name: 'United Kingdom', code: 'GB' },
    { name: 'United States', code: 'US' },
    { name: 'United States Minor Outlying Islands', code: 'UM' },
    { name: 'Uruguay', code: 'UY' },
    { name: 'Uzbekistan', code: 'UZ' },
    { name: 'Vanuatu', code: 'VU' },
    { name: 'Venezuela', code: 'VE' },
    { name: 'Viet Nam', code: 'VN' },
    { name: 'Virgin Islands, British', code: 'VG' },
    { name: 'Virgin Islands, U.S.', code: 'VI' },
    { name: 'Wallis and Futuna', code: 'WF' },
    { name: 'Western Sahara', code: 'EH' },
    { name: 'Yemen', code: 'YE' },
    { name: 'Zambia', code: 'ZM' },
    { name: 'Zimbabwe', code: 'ZW' }
]

//https://www.html-code-generator.com/javascript/json/currency-name (length 164)
export const currencies = [
    { name: "Afghan Afghani", code: "AFA" },
    { name: "Albanian Lek", code: "ALL" },
    { name: "Algerian Dinar", code: "DZD" },
    { name: "Angolan Kwanza", code: "AOA" },
    { name: "Argentine Peso", code: "ARS" },
    { name: "Armenian Dram", code: "AMD" },
    { name: "Aruban Florin", code: "AWG" },
    { name: "Australian Dollar", code: "AUD" },
    { name: "Azerbaijani Manat", code: "AZN" },
    { name: "Bahamian Dollar", code: "BSD" },
    { name: "Bahraini Dinar", code: "BHD" },
    { name: "Bangladeshi Taka", code: "BDT" },
    { name: "Barbadian Dollar", code: "BBD" },
    { name: "Belarusian Ruble", code: "BYR" },
    { name: "Belgian Franc", code: "BEF" },
    { name: "Belize Dollar", code: "BZD" },
    { name: "Bermudan Dollar", code: "BMD" },
    { name: "Bhutanese Ngultrum", code: "BTN" },
    { name: "Bitcoin", code: "BTC" },
    { name: "Bolivian Boliviano", code: "BOB" },
    { name: "Bosnia-Herzegovina Convertible Mark", code: "BAM" },
    { name: "Botswanan Pula", code: "BWP" },
    { name: "Brazilian Real", code: "BRL" },
    { name: "British Pound Sterling", code: "GBP" },
    { name: "Brunei Dollar", code: "BND" },
    { name: "Bulgarian Lev", code: "BGN" },
    { name: "Burundian Franc", code: "BIF" },
    { name: "Cambodian Riel", code: "KHR" },
    { name: "Canadian Dollar", code: "CAD" },
    { name: "Cape Verdean Escudo", code: "CVE" },
    { name: "Cayman Islands Dollar", code: "KYD" },
    { name: "CFA Franc BCEAO", code: "XOF" },
    { name: "CFA Franc BEAC", code: "XAF" },
    { name: "CFP Franc", code: "XPF" },
    { name: "Chilean Peso", code: "CLP" },
    { name: "Chinese Yuan", code: "CNY" },
    { name: "Colombian Peso", code: "COP" },
    { name: "Comorian Franc", code: "KMF" },
    { name: "Congolese Franc", code: "CDF" },
    { name: "Costa Rican ColÃ³n", code: "CRC" },
    { name: "Croatian Kuna", code: "HRK" },
    { name: "Cuban Convertible Peso", code: "CUC" },
    { name: "Czech Republic Koruna", code: "CZK" },
    { name: "Danish Krone", code: "DKK" },
    { name: "Djiboutian Franc", code: "DJF" },
    { name: "Dominican Peso", code: "DOP" },
    { name: "East Caribbean Dollar", code: "XCD" },
    { name: "Egyptian Pound", code: "EGP" },
    { name: "Eritrean Nakfa", code: "ERN" },
    { name: "Estonian Kroon", code: "EEK" },
    { name: "Ethiopian Birr", code: "ETB" },
    { name: "Euro", code: "EUR" },
    { name: "Falkland Islands Pound", code: "FKP" },
    { name: "Fijian Dollar", code: "FJD" },
    { name: "Gambian Dalasi", code: "GMD" },
    { name: "Georgian Lari", code: "GEL" },
    { name: "German Mark", code: "DEM" },
    { name: "Ghanaian Cedi", code: "GHS" },
    { name: "Gibraltar Pound", code: "GIP" },
    { name: "Greek Drachma", code: "GRD" },
    { name: "Guatemalan Quetzal", code: "GTQ" },
    { name: "Guinean Franc", code: "GNF" },
    { name: "Guyanaese Dollar", code: "GYD" },
    { name: "Haitian Gourde", code: "HTG" },
    { name: "Honduran Lempira", code: "HNL" },
    { name: "Hong Kong Dollar", code: "HKD" },
    { name: "Hungarian Forint", code: "HUF" },
    { name: "Icelandic KrÃ³na", code: "ISK" },
    { name: "Indian Rupee", code: "INR" },
    { name: "Indonesian Rupiah", code: "IDR" },
    { name: "Iranian Rial", code: "IRR" },
    { name: "Iraqi Dinar", code: "IQD" },
    { name: "Israeli New Sheqel", code: "ILS" },
    { name: "Italian Lira", code: "ITL" },
    { name: "Jamaican Dollar", code: "JMD" },
    { name: "Japanese Yen", code: "JPY" },
    { name: "Jordanian Dinar", code: "JOD" },
    { name: "Kazakhstani Tenge", code: "KZT" },
    { name: "Kenyan Shilling", code: "KES" },
    { name: "Kuwaiti Dinar", code: "KWD" },
    { name: "Kyrgystani Som", code: "KGS" },
    { name: "Laotian Kip", code: "LAK" },
    { name: "Latvian Lats", code: "LVL" },
    { name: "Lebanese Pound", code: "LBP" },
    { name: "Lesotho Loti", code: "LSL" },
    { name: "Liberian Dollar", code: "LRD" },
    { name: "Libyan Dinar", code: "LYD" },
    { name: "Lithuanian Litas", code: "LTL" },
    { name: "Macanese Pataca", code: "MOP" },
    { name: "Macedonian Denar", code: "MKD" },
    { name: "Malagasy Ariary", code: "MGA" },
    { name: "Malawian Kwacha", code: "MWK" },
    { name: "Malaysian Ringgit", code: "MYR" },
    { name: "Maldivian Rufiyaa", code: "MVR" },
    { name: "Mauritanian Ouguiya", code: "MRO" },
    { name: "Mauritian Rupee", code: "MUR" },
    { name: "Mexican Peso", code: "MXN" },
    { name: "Moldovan Leu", code: "MDL" },
    { name: "Mongolian Tugrik", code: "MNT" },
    { name: "Moroccan Dirham", code: "MAD" },
    { name: "Mozambican Metical", code: "MZM" },
    { name: "Myanmar Kyat", code: "MMK" },
    { name: "Namibian Dollar", code: "NAD" },
    { name: "Nepalese Rupee", code: "NPR" },
    { name: "Netherlands Antillean Guilder", code: "ANG" },
    { name: "New Taiwan Dollar", code: "TWD" },
    { name: "New Zealand Dollar", code: "NZD" },
    { name: "Nicaraguan CÃ³rdoba", code: "NIO" },
    { name: "Nigerian Naira", code: "NGN" },
    { name: "North Korean Won", code: "KPW" },
    { name: "Norwegian Krone", code: "NOK" },
    { name: "Omani Rial", code: "OMR" },
    { name: "Pakistani Rupee", code: "PKR" },
    { name: "Panamanian Balboa", code: "PAB" },
    { name: "Papua New Guinean Kina", code: "PGK" },
    { name: "Paraguayan Guarani", code: "PYG" },
    { name: "Peruvian Nuevo Sol", code: "PEN" },
    { name: "Philippine Peso", code: "PHP" },
    { name: "Polish Zloty", code: "PLN" },
    { name: "Qatari Rial", code: "QAR" },
    { name: "Romanian Leu", code: "RON" },
    { name: "Russian Ruble", code: "RUB" },
    { name: "Rwandan Franc", code: "RWF" },
    { name: "Salvadoran ColÃ³n", code: "SVC" },
    { name: "Samoan Tala", code: "WST" },
    { name: "Saudi Riyal", code: "SAR" },
    { name: "Serbian Dinar", code: "RSD" },
    { name: "Seychellois Rupee", code: "SCR" },
    { name: "Sierra Leonean Leone", code: "SLL" },
    { name: "Singapore Dollar", code: "SGD" },
    { name: "Slovak Koruna", code: "SKK" },
    { name: "Solomon Islands Dollar", code: "SBD" },
    { name: "Somali Shilling", code: "SOS" },
    { name: "South African Rand", code: "ZAR" },
    { name: "South Korean Won", code: "KRW" },
    { name: "Special Drawing Rights", code: "XDR" },
    { name: "Sri Lankan Rupee", code: "LKR" },
    { name: "St. Helena Pound", code: "SHP" },
    { name: "Sudanese Pound", code: "SDG" },
    { name: "Surinamese Dollar", code: "SRD" },
    { name: "Swazi Lilangeni", code: "SZL" },
    { name: "Swedish Krona", code: "SEK" },
    { name: "Swiss Franc", code: "CHF" },
    { name: "Syrian Pound", code: "SYP" },
    { name: "São Tomé and Príncipe Dobra", code: "STD" },
    { name: "Tajikistani Somoni", code: "TJS" },
    { name: "Tanzanian Shilling", code: "TZS" },
    { name: "Thai Baht", code: "THB" },
    { name: "Tongan Pa'anga", code: "TOP" },
    { name: "Trinidad & Tobago Dollar", code: "TTD" },
    { name: "Tunisian Dinar", code: "TND" },
    { name: "Turkish Lira", code: "TRY" },
    { name: "Turkmenistani Manat", code: "TMT" },
    { name: "Ugandan Shilling", code: "UGX" },
    { name: "Ukrainian Hryvnia", code: "UAH" },
    { name: "United Arab Emirates Dirham", code: "AED" },
    { name: "Uruguayan Peso", code: "UYU" },
    { name: "US Dollar", code: "USD" },
    { name: "Uzbekistan Som", code: "UZS" },
    { name: "Vanuatu Vatu", code: "VUV" },
    { name: "Venezuelan BolÃvar", code: "VEF" },
    { name: "Vietnamese Dong", code: "VND" },
    { name: "Yemeni Rial", code: "YER" },
    { name: "Zambian Kwacha", code: "ZMK" }
]